// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Context struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type ContextMessage struct {
	Ordering  pgtype.Int8
	ID        pgtype.UUID
	Role      string
	Content   string
	CreatedAt pgtype.Timestamp
	ContextID pgtype.UUID
}

type ContextSource struct {
	Ordering        pgtype.Int8
	ContextID       pgtype.UUID
	SourceContextID pgtype.UUID
}

type Document struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type DocumentChunk struct {
	ID         pgtype.UUID
	DocumentID pgtype.UUID
	Fragment   pgtype.Text
	Embedding  pgvector.Vector
	CreatedAt  pgtype.Timestamp
}
