on:
  push:
    branches : [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: golangci/golangci-lint-action@v6
